### ISSUE TITLE
site crashes on iOS 17 Safari

### ISSUE THREAD

**Issue by eltigerchino** [sveltejs/learn.svelte.dev#493]
The tutorial, without interaction, automatically refreshes, then crashes on iOS 17 Safari.

https://learn.svelte.dev/tutorial/welcome-to-svelte

Edit: the crash seems to occur once the dev container has finished booting up.

https://github.com/sveltejs/learn.svelte.dev/assets/54401897/db1f39fe-5ece-4044-9275-f6311f555f2e

**System Info**
iOS 17.0 (21A5319a)

**Comment by sgb-io** [comment]
Also experiencing this on iOS 16.6.1.

**Comment by EricSimons** [comment]
Hi all, Eric from StackBlitz here- this is a limitation on iOS' end regarding memory available to webpages. This _might_ be fixed in the latest iOS 17 release but I haven't been able to test it yet. If someone else who has 17 can check that'd be helpful!

**Comment by s3812497** [comment]
Hi Eric. Unfortunately, it's still not fixed. Tested on iOS 17.0.1.

**Comment by sgb-io** [comment]
Hi @EricSimons, can you elaborate at all? It sounds like StackBlitz just doesn't work at all on iOS?

If that's the case, with respect, I'd suggest that learn.svelte.dev should consider other options. A totally broken website at the front of the tutorial doesn't seem very convincing to potential Svelte adopters. It's a difficult sell within organisations like this too.

**Comment by EricSimons** [comment]
It completely depends on how much memory Safari is willing to allocate to the current browser tab, which tends to be extremely conservative. This is not an issue on Android browsers though so the good news is that doesn't seem to be a hardware limitation. It's expected that new browser engines will be able to [land on iOS soon](https://9to5mac.com/2023/02/07/new-iphone-browsers/) which will help solve this issue. On our side, we're exploring further ways to reduce memory usage but this seems to be a fundamental limitation in Safari that will be hard to work around downstream.

Regarding SvelteKit's learn tutorial- until iOS Safari improves their memory usage story, I think a reasonable workaround would be making the tutorial run in a "static" mode when running on iOS Safari. Having it be interactive would be ideal of course, but the core concepts would still be relayed to learners similar to other tutorials / guides.

**Comment by mdevils** [comment]
Is there a way to disable whatever eats so much memory? I just want to read the tutorial and it keeps crashing. Is there a tutorial in PDF format so I can finally get an idea about what Svelte is?

**Comment by kane81** [comment]
This is still happening on iOS 17.2.1 (iPhone 12)
Using Chrome or Safari on the phone.
Any fixes?

**Comment by JPVan** [comment]
As a temporary solution until Apple allows other browsers (maybe never) could this website check for iOS and not load a web container? Or on all devices not load web container until the user selects Editor from the Tutorial / Editor switch? Then it’s still obviously broken by Apple but also still partly usable for those on iOS.

**Comment by eltigerchino** [comment]
closed as duplicate of https://github.com/sveltejs/learn.svelte.dev/issues/416
